# Generated by Django 4.1 on 2023-10-10 17:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='PublishedPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.URLField(blank=True, max_length=250, null=True)),
                ('imagelink', models.ImageField(blank=True, null=True, upload_to='images/designs/')),
                ('message', models.TextField(max_length=1000)),
                ('published_date', models.DateTimeField(blank=True, null=True)),
                ('fblink', models.URLField(blank=True, max_length=100, null=True)),
                ('fb_post_id', models.CharField(blank=True, max_length=40, null=True)),
                ('like_count', models.IntegerField(blank=True, default=0, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pubposts', to='posts.category')),
                ('scheduled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-published_date',),
            },
        ),
        migrations.CreateModel(
            name='Quotes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quote', models.TextField(max_length=1000)),
                ('lang', models.CharField(choices=[('AR', 'AR'), ('EN', 'EN')], default='AR', max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Share',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(blank=True, null=True)),
                ('post_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='posts.publishedpost')),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagelink', models.URLField(max_length=250)),
                ('design_link', models.ImageField(blank=True, null=True, upload_to='images/designs/')),
                ('message', models.TextField(max_length=1000)),
                ('date_to_publish', models.DateTimeField(blank=True, null=True)),
                ('schedule', models.BooleanField(default='False')),
                ('published', models.BooleanField(default='False')),
                ('timezone', models.CharField(blank=True, max_length=150, null=True)),
                ('access_token', models.CharField(blank=True, max_length=250, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.category')),
                ('scheduled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('date_to_publish',),
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagelink', models.URLField(max_length=250)),
                ('design_link', models.ImageField(blank=True, null=True, upload_to='images/designs/')),
                ('message', models.TextField(max_length=1000)),
                ('date', models.DateTimeField(auto_now=True)),
                ('published', models.BooleanField(default='False')),
                ('design', models.BooleanField(default='False')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='posts.category')),
            ],
            options={
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_id', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('comment_by', models.CharField(blank=True, max_length=200, null=True)),
                ('comment_by_profile', models.CharField(blank=True, max_length=200, null=True)),
                ('comment', models.CharField(blank=True, max_length=100, null=True)),
                ('post_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='posts.publishedpost')),
            ],
        ),
        migrations.CreateModel(
            name='AlmazadiProducts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_title', models.CharField(blank=True, max_length=500, null=True)),
                ('imagelink', models.URLField(blank=True, max_length=250, null=True)),
                ('add_link', models.URLField(blank=True, max_length=250, null=True, unique=True)),
                ('edit_link', models.URLField(blank=True, max_length=250, null=True)),
                ('owner', models.CharField(blank=True, max_length=150, null=True)),
                ('message', models.TextField(max_length=1000)),
                ('created_post', models.BooleanField(default=False)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.category')),
            ],
        ),
    ]
