# Generated by Django 4.1 on 2023-10-26 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publishedpost',
            name='imagelink',
        ),
    ]
