# Generated by Django 4.2.7 on 2023-12-28 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='jobtitle',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
