# Generated by Django 4.2.7 on 2023-12-06 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_product_old_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='System_FQA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ar_question', models.CharField(max_length=100)),
                ('en_question', models.CharField(max_length=100)),
                ('ar_answer', models.TextField()),
                ('en_answer', models.TextField()),
            ],
        ),
    ]
