# Generated by Django 4.2.7 on 2023-12-06 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_system_fqa'),
    ]

    operations = [
        migrations.DeleteModel(
            name='System_FQA',
        ),
    ]
