# Generated by Django 4.2.7 on 2023-12-06 12:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_delete_system_fqa'),
    ]

    operations = [
        migrations.CreateModel(
            name='System_FQA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ar_question', models.CharField(max_length=100)),
                ('en_question', models.CharField(max_length=100)),
                ('ar_answer', models.TextField()),
                ('en_answer', models.TextField()),
                ('system', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.medicalsystem')),
            ],
        ),
    ]
