# Generated by Django 4.2.7 on 2023-12-10 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_medicalsystem_tags'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestClinicSystemPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_created=True)),
                ('name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('clinic_count', models.PositiveIntegerField()),
                ('departement_count', models.PositiveIntegerField()),
                ('doctors_count', models.PositiveIntegerField()),
                ('users_count', models.PositiveIntegerField()),
            ],
        ),
    ]
