# Generated by Django 4.2.7 on 2023-12-10 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_requestclinicsystempackage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestclinicsystempackage',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
