# Generated by Django 4.2.7 on 2023-12-10 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_alter_requestclinicsystempackage_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestclinicsystempackage',
            name='details',
            field=models.TextField(blank=True, null=True),
        ),
    ]
