# Generated by Django 4.2.7 on 2023-12-12 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0011_requesthospitalsystempackage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='requesthospitalsystempackage',
            old_name='hosital',
            new_name='hosbital',
        ),
    ]
