# Generated by Django 4.2.7 on 2023-12-27 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0015_alter_cart_products'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='products',
        ),
    ]
