# Generated by Django 4.2.7 on 2023-11-30 12:41

import crmsb.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_resized.forms


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, choices=[('MR', 'MR'), ('MRS', 'MRS')], max_length=25, null=True)),
                ('first_name', models.CharField(blank=True, max_length=120, null=True)),
                ('middle_name', models.CharField(blank=True, max_length=120, null=True)),
                ('last_name', models.CharField(blank=True, max_length=120, null=True)),
                ('gender', models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10, null=True)),
                ('lead_referral_source', models.CharField(blank=True, max_length=120, null=True)),
                ('company', models.CharField(max_length=120)),
                ('address', models.CharField(blank=True, max_length=190, null=True)),
                ('street', models.CharField(blank=True, max_length=190, null=True)),
                ('land_phone_number', models.CharField(max_length=20)),
                ('email', models.CharField(blank=True, max_length=120, null=True)),
                ('website', models.CharField(blank=True, max_length=190, null=True)),
                ('Situation', models.CharField(blank=True, choices=[('Prospect', 'Prospect'), ('Email Sent', 'Email Sent'), ('Active', 'Active'), ('Expired', 'Expired'), ('Suspended', 'Suspended')], default='Prospect', max_length=100, null=True)),
                ('background_info', models.TextField(blank=True, max_length=500, null=True)),
                ('last_contact_date', models.DateTimeField(blank=True, null=True)),
                ('facebook_url', models.CharField(blank=True, max_length=150, null=True)),
                ('instagram_url', models.CharField(blank=True, max_length=150, null=True)),
                ('twitter_url', models.CharField(blank=True, max_length=150, null=True)),
                ('linkedin_url', models.CharField(blank=True, max_length=150, null=True)),
                ('skype_url', models.CharField(blank=True, max_length=150, null=True)),
                ('slug', models.SlugField(blank=True, null=True, verbose_name='slug')),
            ],
        ),
        migrations.CreateModel(
            name='Industry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Whatsapp_Template',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=25)),
                ('type', models.CharField(choices=[('PDF', 'PDF'), ('VIDEO', 'VIDEO'), ('TEXT', 'TEXT'), ('IMAGE', 'IMAGE')], default='TEXT', max_length=10)),
                ('message', crmsb.fields.NonStrippingTextField(max_length=1000)),
                ('file_upload', models.FileField(blank=True, null=True, upload_to='whatsapp_templates/')),
                ('language', models.CharField(blank=True, choices=[('AR', 'AR'), ('EN', 'EN'), ('FR', 'FR')], max_length=2, null=True)),
                ('date', models.DateField(auto_now_add=True)),
                ('template_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Whatsapp_Messages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('PDF', 'PDF'), ('VIDEO', 'VIDEO'), ('TEXT', 'TEXT'), ('IMAGE', 'IMAGE')], default='TEXT', max_length=10)),
                ('message', models.TextField(max_length=1000)),
                ('file_upload', models.FileField(blank=True, null=True, upload_to='whatsapp_templates/')),
                ('date', models.DateField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='whatappmsg', to='crmsb.customer')),
            ],
        ),
        migrations.CreateModel(
            name='Testimonials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', django_resized.forms.ResizedImageField(blank=True, crop=None, default='home/images/testimonials/defaults_testimonials.WEBP', force_format='WEBP', keep_meta=True, null=True, quality=80, scale=None, size=[1920, 1080], upload_to='home/images/testimonials/')),
                ('name', models.CharField(max_length=50)),
                ('jobtitle', models.CharField(max_length=50)),
                ('comment', models.TextField()),
                ('active', models.BooleanField(default=False)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='testimonials', to='crmsb.customer')),
            ],
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField(max_length=500)),
                ('date', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crmsb.customer')),
                ('writer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Customer_Email',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=50)),
                ('message', models.TextField(max_length=1000)),
                ('file_upload', models.FileField(blank=True, null=True, upload_to='')),
                ('date', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crmsb.customer')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='customer',
            name='industry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='industry_type', to='crmsb.industry'),
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150)),
                ('phone_number', models.CharField(max_length=20)),
                ('position', models.CharField(max_length=50)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crmsb.customer')),
            ],
        ),
    ]
