# Generated by Django 4.2.7 on 2023-12-01 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crmsb', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='whatsapp_messages',
            name='type',
            field=models.CharField(choices=[('IMAGE', 'IMAGE'), ('PDF', 'PDF'), ('TEXT', 'TEXT'), ('VIDEO', 'VIDEO')], default='TEXT', max_length=10),
        ),
        migrations.AlterField(
            model_name='whatsapp_template',
            name='type',
            field=models.CharField(choices=[('IMAGE', 'IMAGE'), ('PDF', 'PDF'), ('TEXT', 'TEXT'), ('VIDEO', 'VIDEO')], default='TEXT', max_length=10),
        ),
    ]
