# Generated by Django 4.2.7 on 2024-01-28 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crmsb', '0003_alter_whatsapp_messages_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='whatsapp_messages',
            name='type',
            field=models.CharField(choices=[('IMAGE', 'IMAGE'), ('PDF', 'PDF'), ('TEXT', 'TEXT'), ('VIDEO', 'VIDEO')], default='TEXT', max_length=10),
        ),
        migrations.AlterField(
            model_name='whatsapp_template',
            name='type',
            field=models.CharField(choices=[('IMAGE', 'IMAGE'), ('PDF', 'PDF'), ('TEXT', 'TEXT'), ('VIDEO', 'VIDEO')], default='TEXT', max_length=10),
        ),
    ]
