# Generated by Django 4.2.7 on 2023-12-06 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crmsb', '0012_customer_logo_alter_whatsapp_messages_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='expert',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='whatsapp_messages',
            name='type',
            field=models.CharField(choices=[('VIDEO', 'VIDEO'), ('TEXT', 'TEXT'), ('PDF', 'PDF'), ('IMAGE', 'IMAGE')], default='TEXT', max_length=10),
        ),
        migrations.AlterField(
            model_name='whatsapp_template',
            name='type',
            field=models.CharField(choices=[('VIDEO', 'VIDEO'), ('TEXT', 'TEXT'), ('PDF', 'PDF'), ('IMAGE', 'IMAGE')], default='TEXT', max_length=10),
        ),
    ]
