# Generated by Django 4.2.7 on 2023-12-26 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crmsb', '0040_alter_whatsapp_messages_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='whatsapp_messages',
            name='type',
            field=models.CharField(choices=[('IMAGE', 'IMAGE'), ('PDF', 'PDF'), ('VIDEO', 'VIDEO'), ('TEXT', 'TEXT')], default='TEXT', max_length=10),
        ),
        migrations.AlterField(
            model_name='whatsapp_template',
            name='type',
            field=models.CharField(choices=[('IMAGE', 'IMAGE'), ('PDF', 'PDF'), ('VIDEO', 'VIDEO'), ('TEXT', 'TEXT')], default='TEXT', max_length=10),
        ),
    ]
