# Generated by Django 4.2.7 on 2023-12-28 18:56

from django.db import migrations, models
import django_resized.forms


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('subject', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50)),
                ('phone_number', models.CharField(max_length=50)),
                ('message', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Cooldown',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', django_resized.forms.ResizedImageField(blank=True, crop=None, default='images/slider/defaults_products.WEBP', force_format='WEBP', keep_meta=True, null=True, quality=80, scale=None, size=[1920, 1080], upload_to='images/slider/')),
                ('en_offer', models.CharField(blank=True, max_length=50, null=True)),
                ('ar_offer', models.CharField(blank=True, max_length=50, null=True)),
                ('en_bigTitle', models.CharField(blank=True, max_length=150, null=True)),
                ('ar_bigTitle', models.CharField(blank=True, max_length=150, null=True)),
                ('en_description', models.CharField(blank=True, max_length=50, null=True)),
                ('ar_description', models.CharField(blank=True, max_length=50, null=True)),
                ('end_time', models.DateField(blank=True, null=True)),
                ('active', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='FQA_About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ar_question', models.CharField(max_length=100)),
                ('en_question', models.CharField(max_length=100)),
                ('ar_answer', models.TextField()),
                ('en_answer', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='MainSlider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', django_resized.forms.ResizedImageField(blank=True, crop=None, default='images/slider/defaults_products.WEBP', force_format='WEBP', keep_meta=True, null=True, quality=80, scale=None, size=[1920, 1080], upload_to='images/slider/')),
                ('en_title', models.CharField(max_length=150)),
                ('ar_title', models.CharField(max_length=150)),
                ('active', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='sitedata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', django_resized.forms.ResizedImageField(blank=True, crop=None, default='images/logo.WEBP', force_format='WEBP', keep_meta=True, null=True, quality=80, scale=None, size=[1920, 1080], upload_to='images/logo/')),
                ('fqa_image', django_resized.forms.ResizedImageField(blank=True, crop=None, default='images/logo.WEBP', force_format='WEBP', keep_meta=True, null=True, quality=80, scale=None, size=[1920, 1080], upload_to='images/sitedata/')),
                ('phone_number_1', models.CharField(blank=True, max_length=50, null=True)),
                ('phone_number_2', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.EmailField(blank=True, max_length=75, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('map_link', models.URLField(blank=True, null=True)),
                ('facebook', models.CharField(blank=True, max_length=50, null=True)),
                ('youtube', models.CharField(blank=True, max_length=50, null=True)),
                ('twitter', models.CharField(blank=True, max_length=50, null=True)),
                ('linkedin', models.CharField(blank=True, max_length=50, null=True)),
                ('instagram', models.CharField(blank=True, max_length=50, null=True)),
                ('en_about_us_footer', models.TextField(max_length=120)),
                ('en_video', models.CharField(blank=True, max_length=100, null=True)),
                ('ar_video', models.CharField(blank=True, max_length=100, null=True)),
                ('ar_video_image', django_resized.forms.ResizedImageField(blank=True, crop=None, default='images/logo.WEBP', force_format='WEBP', keep_meta=True, null=True, quality=80, scale=None, size=[1920, 1080], upload_to='images/sitedata/')),
                ('en_video_image', django_resized.forms.ResizedImageField(blank=True, crop=None, default='images/logo.WEBP', force_format='WEBP', keep_meta=True, null=True, quality=80, scale=None, size=[1920, 1080], upload_to='images/sitedata/')),
            ],
        ),
    ]
