# Generated by Django 4.2.7 on 2023-11-29 13:41

from django.db import migrations, models
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='sitedata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', django_resized.forms.ResizedImageField(blank=True, crop=None, default='home/images/logo.WEBP', force_format='WEBP', keep_meta=True, null=True, quality=80, scale=None, size=[1920, 1080], upload_to='home/images/')),
                ('phone_number_1', models.CharField(blank=True, max_length=50, null=True)),
                ('phone_number_2', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.EmailField(blank=True, max_length=75, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('map_link', models.URLField(blank=True, null=True)),
                ('facebook', models.CharField(blank=True, max_length=50, null=True)),
                ('youtube', models.CharField(blank=True, max_length=50, null=True)),
                ('twitter', models.CharField(blank=True, max_length=50, null=True)),
                ('linkedin', models.CharField(blank=True, max_length=50, null=True)),
                ('instagram', models.CharField(blank=True, max_length=50, null=True)),
                ('about_us_footer', models.TextField(max_length=120)),
            ],
        ),
    ]
