# Generated by Django 4.2.7 on 2023-12-01 11:17

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitedata',
            name='logo',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, default='images/logo.WEBP', force_format='WEBP', keep_meta=True, null=True, quality=80, scale=None, size=[1920, 1080], upload_to='images/logo/'),
        ),
    ]
