# Generated by Django 4.2.7 on 2023-11-28 16:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_rename_description_product_ar_description_and_more'),
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainslider',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='products.medicalsystem'),
        ),
        migrations.AddField(
            model_name='mainslider',
            name='title',
            field=models.CharField(default=1, max_length=150),
            preserve_default=False,
        ),
    ]
