# Generated by Django 4.2.7 on 2023-11-29 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_sitedata'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sitedata',
            old_name='about_us_footer',
            new_name='ar_about_us_footer',
        ),
        migrations.AddField(
            model_name='sitedata',
            name='en_about_us_footer',
            field=models.TextField(default=1, max_length=120),
            preserve_default=False,
        ),
    ]
