# Generated by Django 4.2.7 on 2023-11-28 16:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_rename_description_product_ar_description_and_more'),
        ('home', '0002_mainslider_product_mainslider_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainslider',
            name='system',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='products.medicalsystem'),
        ),
        migrations.AlterField(
            model_name='mainslider',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='products.product'),
        ),
    ]
