# Generated by Django 4.2.7 on 2023-11-28 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_mainslider_system_alter_mainslider_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainslider',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
