# Generated by Django 4.2.7 on 2023-11-29 22:24

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_rename_about_us_footer_sitedata_ar_about_us_footer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cooldown',
            name='image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, default='images/slider/defaults_products.WEBP', force_format='WEBP', keep_meta=True, null=True, quality=80, scale=None, size=[1920, 1080], upload_to='images/slider/'),
        ),
        migrations.AlterField(
            model_name='mainslider',
            name='image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, default='images/slider/defaults_products.WEBP', force_format='WEBP', keep_meta=True, null=True, quality=80, scale=None, size=[1920, 1080], upload_to='images/slider/'),
        ),
        migrations.AlterField(
            model_name='sitedata',
            name='logo',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, default='home/images/logo.WEBP', force_format='WEBP', keep_meta=True, null=True, quality=80, scale=None, size=[1920, 1080], upload_to='=images/'),
        ),
    ]
