# Generated by Django 4.2.7 on 2023-11-28 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_mainslider_active'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mainslider',
            old_name='title',
            new_name='en_title',
        ),
        migrations.AddField(
            model_name='mainslider',
            name='ar_title',
            field=models.CharField(default=1, max_length=150),
            preserve_default=False,
        ),
    ]
