# Generated by Django 4.2.7 on 2023-11-28 17:01

from django.db import migrations, models
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_rename_title_mainslider_en_title_mainslider_ar_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cooldown',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', django_resized.forms.ResizedImageField(blank=True, crop=None, default='home/images/slider/defaults_products.WEBP', force_format='WEBP', keep_meta=True, null=True, quality=80, scale=None, size=[1920, 1080], upload_to='home/images/slider/')),
                ('en_offer', models.CharField(blank=True, max_length=50, null=True)),
                ('ar_offer', models.CharField(blank=True, max_length=50, null=True)),
                ('en_bigTitle', models.CharField(blank=True, max_length=150, null=True)),
                ('ar_bigTitle', models.CharField(blank=True, max_length=150, null=True)),
                ('en_description', models.CharField(blank=True, max_length=50, null=True)),
                ('ar_description', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
