# Generated by Django 4.2.7 on 2023-12-06 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_rename_answer_fqa_about_ar_answer_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FQA_About',
        ),
    ]
