# Generated by Django 4.2.7 on 2023-11-28 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_cooldown'),
    ]

    operations = [
        migrations.AddField(
            model_name='cooldown',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
