# Generated by Django 4.2.7 on 2023-11-28 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_cooldown_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='cooldown',
            name='end_time',
            field=models.DateField(blank=True, null=True),
        ),
    ]
