# Generated by Django 4.2.7 on 2023-12-06 10:50

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_fqa_about'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitedata',
            name='fqa_image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, default='images/logo.WEBP', force_format='WEBP', keep_meta=True, null=True, quality=80, scale=None, size=[1920, 1080], upload_to='images/sitedata/'),
        ),
    ]
