# Generated by Django 4.2.7 on 2023-12-06 10:56

from django.db import migrations, models
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_sitedata_fqa_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitedata',
            name='ar_about_us_footer',
        ),
        migrations.AddField(
            model_name='sitedata',
            name='ar_video',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='sitedata',
            name='ar_video_image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, default='images/logo.WEBP', force_format='WEBP', keep_meta=True, null=True, quality=80, scale=None, size=[1920, 1080], upload_to='images/sitedata/'),
        ),
        migrations.AddField(
            model_name='sitedata',
            name='en_video_image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, default='images/logo.WEBP', force_format='WEBP', keep_meta=True, null=True, quality=80, scale=None, size=[1920, 1080], upload_to='images/sitedata/'),
        ),
    ]
