# Generated by Django 4.2.7 on 2023-12-06 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_remove_sitedata_ar_about_us_footer_sitedata_ar_video_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitedata',
            name='en_video',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
