# Generated by Django 4.2.7 on 2023-12-26 16:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0014_cart_completed_cart_created_at'),
        ('home', '0010_sitedata_en_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='cooldown',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='product.product'),
        ),
        migrations.AddField(
            model_name='cooldown',
            name='system',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='product.medicalsystem'),
        ),
    ]
