# Generated by Django 4.1 on 2023-10-10 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='whatsapp_messages',
            name='type',
            field=models.CharField(choices=[('VIDEO', 'VIDEO'), ('PDF', 'PDF'), ('IMAGE', 'IMAGE'), ('TEXT', 'TEXT')], default='TEXT', max_length=10),
        ),
        migrations.AlterField(
            model_name='whatsapp_template',
            name='type',
            field=models.CharField(choices=[('VIDEO', 'VIDEO'), ('PDF', 'PDF'), ('IMAGE', 'IMAGE'), ('TEXT', 'TEXT')], default='TEXT', max_length=10),
        ),
    ]
