# Generated by Django 4.2.7 on 2023-11-29 12:45

from django.db import migrations, models
import django.db.models.deletion
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='whatsapp_messages',
            name='type',
            field=models.CharField(choices=[('TEXT', 'TEXT'), ('PDF', 'PDF'), ('VIDEO', 'VIDEO'), ('IMAGE', 'IMAGE')], default='TEXT', max_length=10),
        ),
        migrations.AlterField(
            model_name='whatsapp_template',
            name='type',
            field=models.CharField(choices=[('TEXT', 'TEXT'), ('PDF', 'PDF'), ('VIDEO', 'VIDEO'), ('IMAGE', 'IMAGE')], default='TEXT', max_length=10),
        ),
        migrations.CreateModel(
            name='Testimonials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', django_resized.forms.ResizedImageField(blank=True, crop=None, default='home/images/testimonials/defaults_testimonials.WEBP', force_format='WEBP', keep_meta=True, null=True, quality=80, scale=None, size=[1920, 1080], upload_to='home/images/testimonials/')),
                ('name', models.CharField(max_length=50)),
                ('jobtitle', models.CharField(max_length=50)),
                ('comment', models.TextField()),
                ('active', models.BooleanField(default=False)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='testimonials', to='crm.customer')),
            ],
        ),
    ]
