# Generated by Django 4.1 on 2023-11-02 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0012_alter_whatsapp_messages_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='whatsapp_messages',
            name='type',
            field=models.CharField(choices=[('PDF', 'PDF'), ('IMAGE', 'IMAGE'), ('VIDEO', 'VIDEO'), ('TEXT', 'TEXT')], default='TEXT', max_length=10),
        ),
        migrations.AlterField(
            model_name='whatsapp_template',
            name='type',
            field=models.CharField(choices=[('PDF', 'PDF'), ('IMAGE', 'IMAGE'), ('VIDEO', 'VIDEO'), ('TEXT', 'TEXT')], default='TEXT', max_length=10),
        ),
    ]
