# Generated by Django 4.2.7 on 2023-11-26 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0015_alter_whatsapp_messages_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='whatsapp_messages',
            name='type',
            field=models.CharField(choices=[('VIDEO', 'VIDEO'), ('IMAGE', 'IMAGE'), ('PDF', 'PDF'), ('TEXT', 'TEXT')], default='TEXT', max_length=10),
        ),
        migrations.AlterField(
            model_name='whatsapp_template',
            name='type',
            field=models.CharField(choices=[('VIDEO', 'VIDEO'), ('IMAGE', 'IMAGE'), ('PDF', 'PDF'), ('TEXT', 'TEXT')], default='TEXT', max_length=10),
        ),
    ]
