# Generated by Django 4.1 on 2023-10-26 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_profile_online_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppDownLoad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_ip', models.CharField(max_length=50, unique=True)),
                ('city', models.CharField(max_length=30)),
                ('regoin', models.CharField(max_length=30)),
                ('country', models.CharField(max_length=30)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
