# Generated by Django 4.1 on 2023-10-27 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0004_alter_appdownload_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appdownload',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
