# Generated by Django 4.1 on 2023-11-02 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0006_alter_appdownload_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='appdownload',
            name='deviceType',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
