# Generated by Django 4.2.7 on 2023-11-26 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0007_appdownload_devicetype'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appdownload',
            options={'verbose_name': 'App Download', 'verbose_name_plural': 'App Downloads'},
        ),
    ]
