# Generated by Django 4.2.7 on 2023-11-28 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_medicalsystem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='medicalsystem',
            old_name='description',
            new_name='ar_description',
        ),
        migrations.RenameField(
            model_name='medicalsystem',
            old_name='name',
            new_name='ar_name',
        ),
        migrations.AddField(
            model_name='medicalsystem',
            name='en_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='medicalsystem',
            name='en_name',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
