# Generated by Django 4.2.7 on 2023-11-28 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_product_category_alter_medicalsystem_image'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Categoies',
            new_name='Categories',
        ),
    ]
