# Generated by Django 4.2.7 on 2023-11-28 15:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_rename_categoies_categories'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='description',
            new_name='ar_description',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='name',
            new_name='ar_name',
        ),
        migrations.AddField(
            model_name='product',
            name='en_description',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='en_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='products', to='products.categories'),
        ),
    ]
