# Generated by Django 4.2.7 on 2023-11-28 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_rename_description_product_ar_description_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categories',
            old_name='name',
            new_name='en_name',
        ),
        migrations.AddField(
            model_name='categories',
            name='ar_name',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
