# Generated by Django 4.2.7 on 2023-11-28 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_rename_name_categories_en_name_categories_ar_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='best_selling',
            field=models.BooleanField(default=False),
        ),
    ]
