# Generated by Django 4.2.7 on 2023-11-28 17:27

from django.db import migrations, models
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_product_best_selling'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', django_resized.forms.ResizedImageField(blank=True, crop=None, default='products/images/testimonials/defaults_products.jpg', force_format='WEBP', keep_meta=True, null=True, quality=80, scale=None, size=[1920, 1080], upload_to='products/images/testimonials/')),
                ('name', models.CharField(max_length=50)),
                ('JobTitle', models.CharField(max_length=50)),
                ('en_description', models.TextField(blank=True, null=True)),
                ('ar_description', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
